#!/bin/sh
set -eu

[ "$#" -eq 4 ] || {
	printf 'usage: %s VERSION REPOSITORY ARTIFACT_DIRECTORY OUTPUT.rb\n' "$0" >&2
	exit 2
}
version=$1
repository=$2
directory=$3
output=$4
printf '%s\n' "$version" | grep -Eq '^v2\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$' || exit 2
case "$version" in
	*-*)
		printf '%s\n' "${version#*-}" | tr . '\n' |
			awk '/^[0-9]+$/ && length > 1 && substr($0, 1, 1) == "0" { bad=1 } END { exit bad }' ||
			exit 2
		;;
esac
printf '%s\n' "$repository" | grep -Eq '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$' || exit 2
case "$directory" in ""|/|.|..|-*|/tmp|/tmp/*|/var/tmp|/var/tmp/*) exit 2 ;; esac
case "$output" in ""|/|.|..|-*|*.tmp|/tmp|/tmp/*|/var/tmp|/var/tmp/*) exit 2 ;; esac
[ -d "$directory" ] && [ ! -L "$directory" ] || exit 1
[ ! -L "$output" ] || exit 2
[ ! -e "$output.tmp" ] && [ ! -L "$output.tmp" ] || {
	printf 'temporary formula path already exists: %s\n' "$output.tmp" >&2
	exit 1
}
trap 'rm -f "$output.tmp"' EXIT HUP INT TERM
checksums="$directory/checksums.txt"
[ -f "$checksums" ] && [ ! -L "$checksums" ] || {
	printf 'missing checksums.txt in %s\n' "$directory" >&2
	exit 1
}

checksum() {
	file=$1
	value=$(awk -v file="$file" '$2 == file { print $1 }' "$checksums")
	[ "$(printf '%s\n' "$value" | awk 'NF { count++ } END { print count+0 }')" -eq 1 ] &&
		printf '%s\n' "$value" | grep -Eq '^[0-9a-f]{64}$' || {
		printf 'missing or invalid checksum for %s\n' "$file" >&2
		exit 1
	}
	printf '%s\n' "$value"
}

darwin_amd64="agefreighter_${version}_darwin_amd64.tar.gz"
darwin_arm64="agefreighter_${version}_darwin_arm64.tar.gz"
linux_amd64="agefreighter_${version}_linux_amd64.tar.gz"
linux_arm64="agefreighter_${version}_linux_arm64.tar.gz"
for file in "$darwin_amd64" "$darwin_arm64" "$linux_amd64" "$linux_arm64"; do
	[ -f "$directory/$file" ] || {
		printf 'missing release archive: %s\n' "$file" >&2
		exit 1
	}
done

base="https://github.com/$repository/releases/download/$version"
cat >"$output.tmp" <<EOF
# Generated by scripts/release/generate-formula.sh; do not edit.
class Agefreighter < Formula
  desc "Validated, resumable graph migration into Apache AGE"
  homepage "https://github.com/$repository"
  version "${version#v}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "$base/$darwin_arm64"
      sha256 "$(checksum "$darwin_arm64")"
    else
      url "$base/$darwin_amd64"
      sha256 "$(checksum "$darwin_amd64")"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "$base/$linux_arm64"
      sha256 "$(checksum "$linux_arm64")"
    else
      url "$base/$linux_amd64"
      sha256 "$(checksum "$linux_amd64")"
    end
  end

  def install
    bin.install "agefreighter"
    bin.install "agefreighter-tools"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agefreighter version")
    assert_match version.to_s, shell_output("#{bin}/agefreighter-tools version")
  end
end
EOF
mv "$output.tmp" "$output"
trap - EXIT HUP INT TERM
