package pggraph

import (
	"errors"
	"fmt"
	"strings"
	"unicode/utf8"
)

type VertexDefinition struct {
	Table string
	Label string
}

type EdgeDefinition struct {
	Table            string
	Label            string
	SourceTable      string
	DestinationTable string
}

type Definition struct {
	Schema   string
	Graph    string
	Vertices []VertexDefinition
	Edges    []EdgeDefinition
}

// DDL returns ordered statements that create the relational storage and then
// its SQL/PGQ property graph declaration. Callers execute them in one
// transaction.
func (definition Definition) DDL() ([]string, error) {
	if err := definition.validate(); err != nil {
		return nil, err
	}

	statements := []string{
		fmt.Sprintf("CREATE SCHEMA IF NOT EXISTS %s", QuoteIdentifier(definition.Schema)),
	}
	for _, vertex := range definition.Vertices {
		statements = append(statements, vertexTableDDL(definition.Schema, vertex.Table))
	}
	for _, edge := range definition.Edges {
		statements = append(statements, edgeTableDDL(definition.Schema, edge))
	}
	statements = append(
		statements,
		"SET LOCAL search_path TO "+QuoteIdentifier(definition.Schema)+", pg_catalog",
		propertyGraphDDL(definition),
	)
	return statements, nil
}

func (definition Definition) validate() error {
	for field, value := range map[string]string{
		"schema": definition.Schema,
		"graph":  definition.Graph,
	} {
		if !validIdentifier(value) {
			return fmt.Errorf("%s must be a valid PostgreSQL identifier of at most 63 bytes", field)
		}
	}
	if len(definition.Vertices) == 0 {
		return errors.New("at least one vertex definition is required")
	}
	tables := make(map[string]struct{}, len(definition.Vertices)+len(definition.Edges))
	labels := make(map[string]struct{}, len(definition.Vertices)+len(definition.Edges))
	vertexTables := make(map[string]struct{}, len(definition.Vertices))
	for index, vertex := range definition.Vertices {
		if err := validateElement(vertex.Table, vertex.Label, tables, labels); err != nil {
			return fmt.Errorf("vertex %d: %w", index, err)
		}
		vertexTables[vertex.Table] = struct{}{}
	}
	for index, edge := range definition.Edges {
		if err := validateElement(edge.Table, edge.Label, tables, labels); err != nil {
			return fmt.Errorf("edge %d: %w", index, err)
		}
		if _, ok := vertexTables[edge.SourceTable]; !ok {
			return fmt.Errorf("edge %d: source table %q is not a vertex table", index, edge.SourceTable)
		}
		if _, ok := vertexTables[edge.DestinationTable]; !ok {
			return fmt.Errorf("edge %d: destination table %q is not a vertex table", index, edge.DestinationTable)
		}
	}
	return nil
}

func validateElement(
	table string,
	label string,
	tables map[string]struct{},
	labels map[string]struct{},
) error {
	if !validIdentifier(table) {
		return errors.New("table must be a valid PostgreSQL identifier of at most 63 bytes")
	}
	if !validIdentifier(label) {
		return errors.New("label must be a valid PostgreSQL identifier of at most 63 bytes")
	}
	if _, exists := tables[table]; exists {
		return fmt.Errorf("duplicate table %q", table)
	}
	if _, exists := labels[label]; exists {
		return fmt.Errorf("duplicate label %q", label)
	}
	tables[table] = struct{}{}
	labels[label] = struct{}{}
	return nil
}

func validIdentifier(identifier string) bool {
	return identifier != "" && len(identifier) <= maxIdentifierBytes &&
		utf8.ValidString(identifier) && !strings.ContainsRune(identifier, '\x00')
}

func vertexTableDDL(schema, table string) string {
	return fmt.Sprintf(`CREATE TABLE %s (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_namespace text NOT NULL,
    external_id text NOT NULL,
    properties jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (source_namespace, external_id)
)`, qualifiedName(schema, table))
}

func edgeTableDDL(schema string, edge EdgeDefinition) string {
	return fmt.Sprintf(`CREATE TABLE %s (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_namespace text NOT NULL,
    external_id text NOT NULL,
    start_id bigint NOT NULL REFERENCES %s (id),
    end_id bigint NOT NULL REFERENCES %s (id),
    properties jsonb NOT NULL DEFAULT '{}'::jsonb
)`, qualifiedName(schema, edge.Table),
		qualifiedName(schema, edge.SourceTable),
		qualifiedName(schema, edge.DestinationTable))
}

func propertyGraphDDL(definition Definition) string {
	vertices := make([]string, 0, len(definition.Vertices))
	for _, vertex := range definition.Vertices {
		vertices = append(vertices, fmt.Sprintf(
			"%s LABEL %s PROPERTIES (source_namespace, external_id, properties)",
			QuoteIdentifier(vertex.Table), QuoteIdentifier(vertex.Label),
		))
	}
	edges := make([]string, 0, len(definition.Edges))
	for _, edge := range definition.Edges {
		edges = append(edges, fmt.Sprintf(
			"%s SOURCE KEY (start_id) REFERENCES %s (id) "+
				"DESTINATION KEY (end_id) REFERENCES %s (id) "+
				"LABEL %s PROPERTIES (source_namespace, external_id, properties)",
			QuoteIdentifier(edge.Table),
			QuoteIdentifier(edge.SourceTable),
			QuoteIdentifier(edge.DestinationTable),
			QuoteIdentifier(edge.Label),
		))
	}

	statement := fmt.Sprintf(
		"CREATE PROPERTY GRAPH %s VERTEX TABLES (%s)",
		QuoteIdentifier(definition.Graph),
		strings.Join(vertices, ", "),
	)
	if len(edges) > 0 {
		statement += " EDGE TABLES (" + strings.Join(edges, ", ") + ")"
	}
	return statement
}

func qualifiedName(schema, name string) string {
	return QuoteIdentifier(schema) + "." + QuoteIdentifier(name)
}
